{% set name = "sqlalchemy2-stubs" %}
{% set version = "0.0.2a20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy2-stubs-{{ version }}.tar.gz
  sha256: 3e96a5bb7d46a368c780ba57dcf2afbe2d3efdd75f7724ae7a859df0b0625f38

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - typing_extensions >=3.7.4

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.sqlalchemy.org
  dev_url: https://github.com/sqlalchemy/sqlalchemy2-stubs
  summary: Typing Stubs for SQLAlchemy 1.4
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
