{% set name = "sqlalchemy2-stubs" %}
{% set version = "0.0.2a17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy2-stubs-{{ version }}.tar.gz
  sha256: d7e1f63f82711c83d49eb6adccbf6bbf3cc94783436c0d34cf7ae49820023046

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - typing-extensions >=3.7.4

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.sqlalchemy.org
  dev_url: https://github.com/sqlalchemy/sqlalchemy2-stubs
  summary: Typing Stubs for SQLAlchemy 1.4
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
